name: "CI"

on:
  push:
    branches:    
      - '*'
      - '*/*'
      - '**'
      - '!master'

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v3"        
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"

      - run: pnpm i --frozen-lockfile
      - run: pnpm run ci
